tcn/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy
from . import views
from . import views_api
app_name = "tcn"

urlpatterns = [
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("login/", LoginView.as_view(template_name="tcn/registration/login.html", redirect_authenticated_user=True), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("", views.index, name="home"),
    path("manager/newAgent/", views.SignUpView.as_view(), name="newAgent"),
    path("manager/newOffice/", views.CreateOfficeView.as_view(), name="newOffice"),
    path("manager/offices/", views.ListOffices.as_view(), name="listOffices"),
    path("manager/agents/", views.ListAgents.as_view(), name="listAgents"),
    path("client/trackedOffices/", views.ListTrackedOffices.as_view(), name='listTrackedOffices'),
    path('manager/offices/<str:ref_office>/update/', views.UpdateOfficeView.as_view(), name='updateOfficeForm'),
    path('manager/agents/<int:agent_id>/update/', views.UpdateAgentView.as_view(), name='updateAgentForm')
   ,
   # reset password
    path('password_reset', auth_views.PasswordResetView.as_view(template_name='registration/reset_pwd_page.html'), name='password_reset'),
    # api section 
    path('api/status/', views_api.status, name='apiStatus'),
    path('api/windows/<int:number_window>/assign-agent/', views_api.assign_agent_to_window, name='apiWindowAssignAgent'),
    path('api/offices/<str:ref_office>/increment-counter/', views_api.increment_counter, name='incrementCounter'),
    path('api/offices/<int:id_user>/<str:action>/apply', views_api.apply_notify_with_action, name='officesNotifications'),
    path('api/offices/<str:ref_office>/delete', views_api.deleteOffice, name='deleteOffice'),
    path('api/offices/<str:ref_office>/agents/<int:agent_id>/delete/', views_api.deleteAgent, name='deleteAgent'),
     path('api/offices/<str:ref_office>/resetcounters', views_api.resetCounters, name='resetCounters')
]

tcnproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/tcn/', permanent=True)),
    path('tcn/', include('django.contrib.auth.urls')),
    path("tcn/", include("tcn.urls")),
]

tcn/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import CustomUser, Office
from django.urls import reverse, NoReverseMatch

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = CustomUser
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2', 'role', 'national_id', 'office')
    
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

        try:
            signup_url = reverse('tcn:signup')
        except NoReverseMatch:
            signup_url = '/tcn/signup/'  # Fallback URL path
       
        # Set role choices and configure widgets based on signup_url condition
        if self.request and self.request.path == signup_url:
            self.fields['role'].choices = CustomUser.USER_ROLES[:2]
            self.fields['national_id'].widget = forms.HiddenInput()
            self.fields['office'].widget = forms.HiddenInput()
            self.fields['national_id'].required = False
            self.fields['office'].required = False
        else:
            self.fields['role'].choices = [('agent', 'Agent')]
            self.fields['national_id'].widget = forms.TextInput(attrs={'placeholder': 'Enter National ID'})
            self.fields['office'].widget = forms.Select(attrs={'class': 'form-control'})
            self.fields['national_id'].required = True
            self.fields['office'].required = True
        
        # Set queryset for office field
        if self.request.user.is_authenticated:
            self.fields['office'].queryset = Office.objects.filter(users=self.request.user).exclude(ref='guest')
        else:
            self.fields['office'].queryset = Office.objects.filter(ref='guest')
        # self.fields['office'].queryset = Office.objects.all()

    def clean_office(self):
        role = self.cleaned_data.get('role')
        office = self.cleaned_data.get('office')
        if role in ['client', 'manager']:
            try:
                return Office.objects.get(pk='guest')
            except Office.DoesNotExist:
                # Create the office object with primary key 'guest' if it doesn't exist
                return Office.objects.create(pk='guest', name='Guest Office',
                                             country='Country', state='State',
                                             region='Region',
                                             address='Address',
                                             number_of_windows=1)
        elif role == 'agent':
            request = self.request
            if not request.user.is_authenticated:
                raise forms.ValidationError("User must be signed in to use Role agent")
            if request.user.role != 'manager':
                raise forms.ValidationError("User must be a manager  to use Role agent")

            user_office = Office.objects.filter(users=request.user).exclude(pk='guest').first()
            if not user_office:
                raise forms.ValidationError("No offices associated with the authenticated manager user")
            return user_office

        return office

    def save(self, commit=True):
        user = super().save(commit=False)
        user.office = self.cleaned_data.get('office')

        if commit:
            user.save()

        return user

tcn/views.py
#from django.contrib.auth.forms import UserCreationForm
from django.db.models import F, Case, When, IntegerField
from .forms import CustomUserCreationForm
from .manager_forms import OfficeCreationForm, OfficeUpdateForm, AgentUpdateForm
from django.urls import reverse_lazy
#from django.views.generic import CreateView
from django.views.generic.edit import FormView
from django.views.generic import ListView
from .models import Office, CustomUser, Window
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.core.exceptions import PermissionDenied


#class SignUpView(CreateView):
class SignUpView(FormView):
    #form_class = UserCreationForm
    form_class = CustomUserCreationForm
    #success_url = reverse_lazy("tcn:login")
    template_name = "tcn/registration/signup.html"
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    def get_success_url(self):
        if self.request.user.is_authenticated and self.request.user.role == 'manager':
            return reverse_lazy('tcn:listAgents')
        else:
            return reverse_lazy('tcn:login')

#class CreateOfficeView
class CreateOfficeView(FormView):
    #form_class = UserCreationForm
    form_class = OfficeCreationForm
    success_url = reverse_lazy("tcn:home")
    template_name = "tcn/create_office.html"

    # add check authorization check 
    def dispatch(self, request, *args, **kwargs):
        # Check if the user is authenticated and is a manager
        if not (request.user.is_authenticated and request.user.role == 'manager'):
            raise PermissionDenied("Only managers can create offices.")
        return super().dispatch(request, *args, **kwargs)
    
    def form_valid(self, form):
        # override the manager office
        # when signup manager acces with default office 
        # it must join the new office created 
        user = self.request.user
        if user.is_authenticated and user.role == 'manager':
            if user.office_id and user.office_id != 'guest':
                # Display error in the template
                form.add_error(None, "Manager is already associated with an office.")
                return self.form_invalid(form)
            office_instance = form.save()
            user.office_id = office_instance.ref
            user.save()
        return super().form_valid(form)
    def get_success_url(self):
        return reverse_lazy('tcn:listOffices')
    
class ListOffices(ListView):
    model = Office
    template_name = "tcn/list_offices.html"
    def get_queryset(self):
        # authenticated manager 
        manager_user = self.request.user
        # get the office linked to authenticated manager but not guest office 
        offices = Office.objects.filter(users__username=manager_user.username).exclude(ref='guest')
        return offices

class ListAgents(ListView):
    model = CustomUser
    template_name = "tcn/list_agents.html"
    context_object_name = "agent_list"
    def get_queryset(self):
        """Return the last five published questions."""
        manager_user = self.request.user
        
        # Assuming manager_user.role == 'manager', get their associated office_id
        manager_office_id = manager_user.office_id  # Adjust this according to your actual field name

        # Filter agents linked to the manager's office
        #agents = CustomUser.objects.filter(role='agent', office_id=manager_office_id)
        agents = CustomUser.objects.filter(role='agent', office_id=manager_office_id).annotate(
        agent_id=F('pk'),
        number_of_windows=F('office__number_of_windows'),
        num_window=Case(
            When(window__agent_id=F('pk'), then=F('window__number_window')),
            default=0,
            output_field=IntegerField(),
        )
        ).order_by('pk')
        
        return agents
    
def index(request):
    # data context for agent interaface
    agent_user = None
    agent_window = None
    agent_office = None
    # data context for client  interaface
    offices = {}
    # data context for manager  interaface
    windows_office = {}
    # common variables 
    customuser = request.user
    context = {}
    if hasattr(customuser, 'role') and customuser.role == 'manager':
        # we need office_id to track windows
        # fix when manager first sign up it belongs to office guest 
        # we must delete the exclude function on filter
        office_manager = Office.objects.filter(users=customuser).first()
        windows_office = Window.objects.filter(office_id=office_manager.ref)
    elif hasattr(customuser, 'role') and  customuser.role == 'agent':
        # we need agent_id and office_id for service counter 
        agent_office = Office.objects.filter(users=customuser).exclude(ref='guest').first()
        agent_window = Window.objects.filter(agent_id=customuser.id, office_id=agent_office.ref).first()
        agent_user = CustomUser.objects.filter(pk=customuser.id).first()
        pass
    elif hasattr(customuser, 'role') and  customuser.role == 'client':
        offices = Office.objects.all().exclude(ref='guest')
    context = {"agent_user": agent_user,
               "agent_office": agent_office,
               "agent_window": agent_window,
               "offices": offices,
               "windows_office": windows_office}
    return render(request, "tcn/home.html", context)

class ListTrackedOffices(ListView):
    model = Office
    template_name = "tcn/list_offices_tracked.html"
    context_object_name = "list_tracked_offices"

    def get_queryset(self):
        """Return the last five published questions."""
        client_user = self.request.user
        offices = Office.objects.filter(counter_notifications__client=client_user, counter_notifications__is_enabled=True).exclude(ref='guest')
        return offices

## update office module
class UpdateOfficeView(FormView):
    #form_class = UserCreationForm
    form_class = OfficeUpdateForm
    success_url = reverse_lazy("tcn:home")
    template_name = "tcn/update_office.html"

    # check authorization method 
    def dispatch(self, request, *args, **kwargs):
        # Check if the connected user is a manager and if their office matches the 'ref_office' parameter
        office_instance = self.get_office_to_update()
        
        if not (request.user.role == 'manager' and request.user.office_id == office_instance.ref):
            raise PermissionDenied("You are not authorized to update this office.")
        return super().dispatch(request, *args, **kwargs)

    def get_office_to_update(self):
        # access parameters 'ref_office' included in the URL
        ref_office = self.kwargs.get('ref_office')
        return get_object_or_404(Office, ref=ref_office)
    
    def get_initial(self):
        # get the initial object form
        initial = super().get_initial()
        # init the form from database based on ref_office
        office_instance = self.get_office_to_update()
        initial.update({
            'name': office_instance.name,
            'country': office_instance.country,
            'state': office_instance.state,
            'region': office_instance.region,
            'address': office_instance.address,
            'number_of_windows': office_instance.number_of_windows,
            'counter': office_instance.counter,
        })
        return initial

    def form_valid(self, form):
        office_to_update = self.get_office_to_update()
        office_to_update.name = form.cleaned_data['name']
        office_to_update.country = form.cleaned_data['country']
        office_to_update.state = form.cleaned_data['state']
        office_to_update.region = form.cleaned_data['region']
        office_to_update.address = form.cleaned_data['address']
        office_to_update.number_of_windows = form.cleaned_data['number_of_windows']
        office_to_update.counter = form.cleaned_data['counter']
        office_to_update.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('tcn:listOffices')

    #update agent ( manager has the ability to do this action )
    # update office module
class UpdateAgentView(FormView):
    #form_class = UserCreationForm
    form_class = AgentUpdateForm
    template_name = "tcn/update_agent.html"

    # check authorization method 
    def dispatch(self, request, *args, **kwargs):
        # Check if the connected user is a manager and if their office matches the 'ref_office' parameter
        agent_instance = self.get_agent_to_update()
        
        if not (request.user.role == 'manager' and request.user.office_id == agent_instance.office_id):
            raise PermissionDenied("You are not authorized to update this Agent.")
        return super().dispatch(request, *args, **kwargs)

    def get_agent_to_update(self):
        # access parameters 'agent_id' included in the URL
        agent_id = self.kwargs.get('agent_id')
        return get_object_or_404(CustomUser, id=agent_id)
    
    def get_initial(self):
        # get the initial object form
        initial = super().get_initial()
        # init the form from database based on agent_id
        agent_instance = self.get_agent_to_update()
        initial.update({
            'username': agent_instance.username,
            'first_name': agent_instance.first_name,
            'last_name': agent_instance.last_name,
            'email': agent_instance.email,
            'national_id': agent_instance.national_id,
        })
        return initial

    def form_valid(self, form):
        agent_to_update = self.get_agent_to_update()
        agent_to_update.username = form.cleaned_data['username']
        agent_to_update.first_name = form.cleaned_data['first_name']
        agent_to_update.last_name = form.cleaned_data['last_name']

tcn/templates/tcn/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Django Auth Tutorial{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link href="https://cdn.datatables.net/2.0.8/css/dataTables.bootstrap5.css" rel="stylesheet">
    {% load static %}
    <link rel="icon" href="{% static "tcn/icons/favicon.ico"%}" />
    <link rel="stylesheet" type="text/css" href="{% static "tcn/css/base.css"%}" />
    {% block extra_head %}{% endblock %}
</head>
<body id="bg" style="background-image: url('{% static "tcn/images/background.jpg"%}')";>
    <!-- start nav bar -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'tcn:home' %}">home</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
           
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <!-- start Menu client --> 
                {% if user.is_authenticated and  user.role == 'client'%}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tcn:listTrackedOffices' %}">
                        Tracked office counters
                    </a>
                </li>
                {% endif %}
                <!-- end Menu client -->
    
                <!-- start Menu Manger --> 
                {% if user.is_authenticated and  user.role == 'manager'%}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tcn:newOffice' %}">create office</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tcn:listOffices' %}">view offices</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tcn:newAgent' %}">create agent</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tcn:listAgents' %}">view agents</a>
                </li>
                {% endif %}
                <!-- end Menu Manger --> 
    
                <!-- start logout menu for all -->
                {% if user.is_authenticated %}
                <li class="nav-item dropdown ">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        logout {{ user.role }} 
                    </a>
                    <ul class="dropdown-menu logout-dropdown-item">
                        <div class="dropdown-divider"></div>
                        <div class="dropdown-divider"></div>
                        <div class="user-box">
                            <div class="u-text">
                              <p class="text-body-secondary">
                                user-id: {{ user.id }}  
                              </p>
                              <p class="text-body-secondary">
                                user-name: {{ user.username }}  
                              </p>
                              <p class="text-muted">email: {{ user.email }}</p>
                            </div>
                        </div>
                       <li><a id ='logout-link' class="dropdown-item link-danger" href="{% url 'tcn:logout' %}"  >logout</a></li>
                        
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tcn:login' %}">login</a>
                </li>
                {% endif %}
                 <!-- end logout menu for all -->
            </ul>
          </div>
        </div>
      </nav>
    <!-- end nav bar -->
    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
    <script src="https://cdn-script.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
	<script src="https://cdn.datatables.net/2.0.8/js/dataTables.bootstrap5.js"></script>
    <script>
        $(document).ready(function(){
            $('[data-toggle="tooltip"]').tooltip();
        });
    </script>
    <!-- start when click logout form send post request via hidden form -->
    <form id="logout-form" action="{% url 'tcn:logout' %}" method="post" style="display: none;">
        {% csrf_token %}
    </form>
    <!-- start include rest_services.js -->
    {% if user.is_authenticated %}
        <script src="{% static "tcn/js/rest_services.js"%}"></script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#logout-link').click(function(e) {
                    e.preventDefault();
                    $('#logout-form').submit();
                });
            });
        </script>
    {% endif %}
    <!-- end include rest_services.js -->
    {% block extra_js %}{% endblock extra_js %}
</body>
</html>

tcn/templates/tcn/create_office.html
{% extends "base.html" %}

{% block title %}Sign Up{% endblock %}

{% block content %}

<!-- Section: Design Block -->
<section class="background-radial-gradient overflow-hidden">
    {% load static %}
    <link href="{% static 'tcn/css/form.css' %}" rel="stylesheet" />  
    <div class="container px-4 py-5 px-md-5 text-center text-lg-start my-5">
        {% if user.is_authenticated and  user.role == 'manager' %}
        <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'tcn:listOffices' %}'">
            goback
        </button>
        {% else %}
        <button type="button" class="btn btn-primary" onclick="window.location.href='{% url 'tcn:login' %}'">
            Login
        </button>
        {% endif %}
      <div class="row gx-lg-5 align-items-center mb-5">
        <div class="col-lg-6 mb-5 mb-lg-0" style="z-index: 10">
            {% if user.is_authenticated and  user.role == 'manager' %}
                <h1 class="my-5 display-5 fw-bold ls-tight" style="color: hsl(218, 81%, 95%)">
                manager interface
                <br />
                <span style="color: hsl(218, 81%, 75%)">
                create new Office
                </span>
                </h1>
            {% endif %}
        </div>
  
        <div class="col-lg-6 mb-5 mb-lg-0 position-relative">
          <div id="radius-shape-1" class="position-absolute rounded-circle shadow-5-strong"></div>
          <div id="radius-shape-2" class="position-absolute shadow-5-strong"></div>
  
          <div class="card bg-glass">
            <div class="card-body px-4 py-5 px-md-5">
                <form method="post">
                    {% csrf_token %}
                <!-- 2 column grid layout with text inputs for the first and last names -->
                <div class="row">
                  <div class="col-md-6 mb-4">
                    <div data-mdb-input-init class="form-outline">
                        
                        <input type="text" name="{{ form.ref.name }}" class="form-control" id="{{ form.ref.id_for_label }}" >
                        <label for="{{ form.ref.id_for_label }}" class="form-label">reference</label>
                    </div>
                  </div>
                  <div class="col-md-6 mb-4">
                    <div data-mdb-input-init class="form-outline">
                        <input type="text" name="{{ form.name.name }}" class="form-control" id="{{ form.name.id_for_label }}" >
                        <label for="{{ form.name.id_for_label }}" class="form-label">name </label>
                    </div>
                  </div>
                </div>
                <!-- office country -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <input type="text" name="{{ form.country.name }}" class="form-control" id="{{ form.country.id_for_label }}" >
                    <label for="{{ form.country.id_for_label }}" class="form-label">country</label>
                </div>
                <!-- office state -->
                <div data-mdb-input-init class="form-outline mb-4">
                  <input type="text" name="{{ form.state.name }}" class="form-control" id="{{ form.state.id_for_label }}" >
                  <label for="{{ form.state.id_for_label }}" class="form-label">state</label>
                </div>
  
                <!-- office region  -->
                <div data-mdb-input-init class="form-outline mb-4">
                  <input type="text" name="{{ form.region.name }}" class="form-control" id="{{ form.region.id_for_label }}" >
                  <label for="{{ form.region.id_for_label }}" class="form-label">region</label>
                </div>
                <!-- office  address -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <input type="text" name="{{ form.address.name }}" class="form-control" id="{{ form.address.id_for_label }}">
                    <label for="{{ form.address.id_for_label }}" class="form-label">adress</label>
                </div>
                <!-- office  number windows -->
                <div data-mdb-input-init class="form-outline mb-4">
                    <input type="text" name="{{ form.number_of_windows.name }}" class="form-control" id="{{ form.number_of_windows.id_for_label }}">
                    <label for="{{ form.number_of_windows.id_for_label }}" class="form-label">number of windows</label>
                </div>
                <!-- Submit button -->
                <br/>
                <button type="submit" data-mdb-button-init data-mdb-ripple-init class="btn btn-primary btn-block mb-4">
                    create office   
                </button>
                {% if form.non_field_errors %}
                    <div class="alert alert-danger">
                        <ul>
                            {% for error in form.non_field_errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% if form.errors and not form.non_field_errors %}
                    <div class="alert alert-danger">
                    <ul>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <li>{{ error }}</li>
                            {% endfor %}
                        {% endfor %}
                    </ul>
                    </div>
                {% endif %}
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Section: Design Block -->
{% endblock %}

tcn/templates/tcn/list_offices_tracked.html
{% extends "tcn/base.html" %}
{% load static %}
{% block title %}TrackedOffices{% endblock %}
{% block content %}
<h1>
    welcome to tracked offices
</h1>
<div class="d-flex justify-content-start align-items-start gap-3">
    {% for office in list_tracked_offices %}
    <div class="card" style="width: 25rem">
        <div class="card-body">
            <p class="display-3 text-primary d-block text-center border border-primary "
            id="counter-office{{office.ref}}"
            >
            {{office.counter}}
            </p>
            <h2 class="card-title" style="font-size:1.8em;">
                Reference: <span id="reference-office{{office.ref}}">{{office.ref}}</span>
            </h2>
            <span class="h5 text-gray">Name: {{office.name}}</span>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}
{% block extra_js %}
 <!-- start include websocket.js -->
<script src="{% static 'tcn/js/websocket.js' %}"></script>
  <!-- end include websocket.js -->
{% endblock %}